---
services:
  - docker

before_install:
  - docker pull rmohta/alpine-vim8:base

script:
  - docker run --rm -it -v ${PWD}/:/root/ rmohta/alpine-vim8:base /bin/sh -c "apk update && apk add git;
      rm -rf /root/.vim/ /root/.vimrc;
      mkdir /root/.vim/;
      mv vimrc autoload /root/.vim/;
      ln -s .vim/vimrc ~/.vimrc;
      vim +\'PlugInstall --sync\' +qa;"
