---
name: CI
'on':
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: "0 1 * * 1"

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Setup test environment
        run: docker pull ghcr.io/toozej/vim-ci:latest

      - name: Run tests
        run: >
          docker run --rm -v /home/runner/work/vimfiles/vimfiles/:/workspace/ ghcr.io/toozej/vim-ci /bin/sh -c
          "ls -lah /workspace/; 
          cp /workspace/vimrc /root/.vim/; cp -r /workspace/autoload /root/.vim/; 
          ln -s /root/.vim/vimrc ~/.vimrc;
          vim +'PlugInstall --sync' +qa;"
